### PR TITLE
daisyUI integration

### PR DESCRIPTION
**Pull request by Alvarado08**
# Description

Added Hungry Rabbit theme color classes into daisyUI config.

## Main changes explained:

- Installed daisyUI
- Updated `tailwind.config.js`
- Added *hungryRabbit* theme nested object: `daisyui` object  > `themes` array

## How to test:

1. check into current branch
2. do `npm install` and `npm start` to run this PR locally
3. Try using daisyUI theme classes to style components
4. Verify daisyUI classes are working correctly
5. Feel free to comment with any suggestions and/or questions

## Screenshots:

Captura de Pantalla 2024-07-23 a la(s) 2 38 55 p m
daisyUI-config

### CODE REVIEW

**Review by cvtqx — COMMENTED** [review]
Daisy UI theme colors work great!

Suggestion - perhaps now with daisy ui configured we should remove the extend block from theme? This one:

Screenshot 2024-07-23 at 9 28 28 PM

 It seems to be redundant

**Comment by Alvarado08** [comment]
@cvtqx I agree! Let me go ahead and remove it from `tailwind.config.js`.

**Review by Alvarado08 — COMMENTED** [review]
@cvtqx `tailwind.config.js` extend block has been removed.

**Review by cvtqx — APPROVED** [review]
Looks good! Thanks for the update!

**Pull request merged**
